name: Inputs and Outputs
on:
    workflow_call:
        inputs:
            dry-run:
                description: "Skip deployment and only print build output"
                type: boolean
                default: false
            target:
                description: "Which environment the workflow will target"
                type: string
                required: true
            tag:
                description: "Release from which to build and deploy"
                type: string
                default: v3
            build-status:
                description: "Choose the build status for the demo"
                type: string
                default: success
        outputs:
            salida: 
                description: "The first output string"
                value: ${{ jobs.deploy.outputs.resultado }}
            
jobs:
    build:
        runs-on: ubuntu-latest
        outputs:
            build-status: ${{ steps.build.outputs.status }}
            tag: ${{ steps.build.outputs.tag }}
        steps:
            -  name: Print GITHUB_OUTPUT path
               run: |
                echo $GITHUB_OUTPUT
               
            - name: Build
              id: build
              run: |
                echo "tag=${{ inputs.tag }}" >> "$GITHUB_OUTPUT"
                echo "status=${{ inputs.build-status }}" >> "$GITHUB_OUTPUT"
    deploy:
        runs-on: ubuntu-latest
        outputs:
            resultado: ${{ steps.deploy.outputs.resultado }}
        needs: build
        if: ${{ !inputs.dry-run && needs.build.outputs.build-status == 'success'}}
        environment: ${{ inputs.target }}
        steps:
            - name: Deploy
              id: deploy
              run: |
                echo "resultado = Deploying to: ${{ inputs.target }} using tag ${{ needs.build.outputs.tag }}"  >> "$GITHUB_OUTPUT"
        