name: Inputs and Outputs
on:
    workflow_call:
        inputs:
            dry-run:
                type: boolean
                default: false
                description: Skip deployment and only print build output
            target:
                type: string
                required: true
                description: Which environment the workflow will target
            tag:
                type: string
                default: v3
                description: Release from which to build and deploy
            build-status:
                type: string
                default: success
                description: Choose the build status for the demo
        outputs:
            result:
                description: Result of deploy job
                value: ${{ jobs.deploy.outputs.result }}

jobs:
    build:
        runs-on: ubuntu-latest
        outputs:
            tag: ${{ steps.build.outputs.tag }}
            build-status: ${{ steps.build.outputs.status }}
        steps:
            - name: Print GITHUB_OUTPUT path
              run: |
                  echo $GITHUB_OUTPUT
            - name: "Build"
              id: build
              run: |
                  echo "tag=${{ inputs.tag }}" >> $GITHUB_OUTPUT
                  echo "status=${{ inputs.build-status }}" >> $GITHUB_OUTPUT

    deploy:
        runs-on: ubuntu-latest
        needs: build
        if: ${{ !inputs.dry-run && needs.build.outputs.build-status == 'success' }}
        environment: ${{ inputs.target }}
        outputs:
          result: ${{ steps.deploy.outputs.result }}
        steps:
            - name: deploy
              id: deploy
              run: |
                  echo "result=Deploying to: ${{ inputs.target }} using tag ${{ needs.build.outputs.tag }}" >> $GITHUB_OUTPUT
