name: External IO Workflow

on:
  workflow_call:
    inputs:
      dry-run:
        required: true
        type: boolean
      target:
        required: true
        type: string
      tag:
        required: true
        type: string
      build-status:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        id: build
        run: |
          echo "tag=${{ inputs.tag }}" >> $GITHUB_OUTPUT
          echo "status=${{ inputs.build-status }}" >> $GITHUB_OUTPUT
    outputs:
      build-status: ${{ steps.build.outputs.status }}
      tag: ${{ inputs.tag }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ needs.build.result == 'success' && inputs.dry-run == false && needs.build.outputs.build-status == 'success' }}
    environment: ${{ inputs.target }}
    steps:
      - name: Deploy
        id: deploy-step
        run: echo "Deploying to '${{ inputs.target }}' using tag '${{ inputs.tag }}'"
    outputs:
      deploy-message: ${{ steps.deploy-step.outputs }}
